const express = require("express");
const router = express.Router();
const authMiddleware = require("../middleware/authMiddleware");
const User = require("../models/User");
const { callOpenRouter } = require("../utils/openrouter");

// Fixed first question — always the same to start every assessment
const FIRST_QUESTION = {
  question: "Which subject do you enjoy the most?",
  category: "interests",
  options: [
    { text: "Science", traits: ["analytical", "research-oriented", "curious"] },
    { text: "Commerce", traits: ["strategic", "business-minded", "numerical"] },
    { text: "Arts", traits: ["creative", "expressive", "imaginative"] },
    { text: "Technology", traits: ["technical", "problem-solver", "innovative"] },
  ],
};

// POST /api/assessment/generate-all-questions — Generate all 10 questions at once
// Q1 is fixed, Q2-Q10 are generated by AI in a single batch call
router.post("/generate-all-questions", authMiddleware, async (req, res) => {
  try {
    const totalQuestions = 10;

    const prompt = `Generate exactly 9 career assessment questions for a student. These questions should explore DIFFERENT aspects of the student's personality and career fit.

Each question MUST explore a DIFFERENT angle from this list (one question per angle):
1. Academic strengths and favorite subjects
2. Problem-solving style and approach
3. Personality traits and temperament
4. Work environment and style preferences
5. Values, motivations, and what drives them
6. Leadership vs teamwork preferences
7. Creativity and innovation style
8. Communication and social preferences
9. Long-term career goals and ambitions

Return EXACTLY this JSON structure:
{
  "questions": [
    {
      "question": "Question text here?",
      "category": "one-word like skills/personality/values/workstyle/goals/leadership/creativity/communication/academics",
      "options": [
        {"text": "Option A text", "traits": ["trait1", "trait2"]},
        {"text": "Option B text", "traits": ["trait1", "trait2"]},
        {"text": "Option C text", "traits": ["trait1", "trait2"]},
        {"text": "Option D text", "traits": ["trait1", "trait2"]}
      ]
    }
  ]
}

Rules:
- Generate exactly 9 questions (they will be questions 2-10; question 1 is pre-set)
- Each question must have exactly 4 options
- Each option must have a "traits" array with 2-3 relevant personality/skill traits
- Make questions engaging, diverse, and relevant to career discovery for Indian students
- DO NOT ask about favorite subject (that's already question 1)
- Options should reveal different career inclinations (science, commerce, arts, tech, medical, etc.)
- Return ONLY the JSON object, nothing else`;

    const aiResponse = await callOpenRouter([
      { role: "user", content: prompt },
    ]);

    // Validate response structure
    if (
      !aiResponse.questions ||
      !Array.isArray(aiResponse.questions) ||
      aiResponse.questions.length < 9
    ) {
      throw new Error("Invalid AI response: expected 9 questions");
    }

    // Validate each question
    const validatedQuestions = [];
    for (const q of aiResponse.questions.slice(0, 9)) {
      if (
        !q.question ||
        !q.options ||
        !Array.isArray(q.options) ||
        q.options.length !== 4
      ) {
        throw new Error("Invalid question structure in AI response");
      }
      for (const opt of q.options) {
        if (!opt.text || !opt.traits || !Array.isArray(opt.traits)) {
          throw new Error("Invalid option structure in AI response");
        }
      }
      validatedQuestions.push({
        question: q.question,
        category: q.category || "general",
        options: q.options,
      });
    }

    // Combine: Q1 (fixed) + Q2-Q10 (AI-generated)
    const allQuestions = [FIRST_QUESTION, ...validatedQuestions];

    return res.status(200).json({
      success: true,
      questions: allQuestions,
      totalQuestions: allQuestions.length,
    });
  } catch (error) {
    console.error("Error generating all questions:", error.message);
    res.status(500).json({
      success: false,
      message: "Something went wrong generating questions. Please try again.",
      error: error.message,
    });
  }
});

// POST /api/assessment/next-question — Generate the next question using AI (kept for backward compat)
router.post("/next-question", authMiddleware, async (req, res) => {
  try {
    const { previousQnA, questionNumber, totalQuestions } = req.body;

    if (!questionNumber || !totalQuestions) {
      return res.status(400).json({
        success: false,
        message: "questionNumber and totalQuestions are required",
      });
    }

    // Question 1: return fixed starter question (no AI call needed)
    if (questionNumber === 1) {
      return res.status(200).json({
        success: true,
        question: FIRST_QUESTION.question,
        category: FIRST_QUESTION.category,
        options: FIRST_QUESTION.options,
      });
    }

    // Questions 2-10: generate dynamically with AI
    if (!previousQnA || !Array.isArray(previousQnA) || previousQnA.length === 0) {
      return res.status(400).json({
        success: false,
        message: "previousQnA is required for questions after the first",
      });
    }

    const qnaHistory = previousQnA
      .map(
        (qna, i) =>
          `Q${i + 1} (${qna.category}): ${qna.question}\nAnswer: ${qna.answer} [Traits: ${qna.traits.join(", ")}]`
      )
      .join("\n\n");

    const aspectsToExplore = [
      "interests and passions",
      "academic strengths and skills",
      "personality traits and temperament",
      "work style and environment preferences",
      "values and motivations",
      "leadership and teamwork style",
      "problem-solving approach",
      "creativity and innovation",
      "long-term career goals",
    ];

    const suggestedAspect = aspectsToExplore[(questionNumber - 2) % aspectsToExplore.length];

    const prompt = `Based on the following career assessment responses from a student, generate the NEXT most relevant career assessment question.

Previous Q&A:
${qnaHistory}

This is question ${questionNumber} of ${totalQuestions}. 
Focus on exploring: ${suggestedAspect}
Make sure this question explores a NEW angle not already covered. Do NOT repeat topics from previous questions.

Return EXACTLY this JSON structure:
{
  "question": "Your question text here?",
  "category": "one-word category like interests/skills/personality/values/workstyle",
  "options": [
    {"text": "Option A text", "traits": ["trait1", "trait2"]},
    {"text": "Option B text", "traits": ["trait1", "trait2"]},
    {"text": "Option C text", "traits": ["trait1", "trait2"]},
    {"text": "Option D text", "traits": ["trait1", "trait2"]}
  ]
}

Rules:
- Generate exactly 4 options
- Each option must have a "traits" array with 2-3 relevant personality/skill traits
- The question should be engaging and relevant to career discovery
- Make options diverse to reveal different career inclinations
- Return ONLY the JSON object, nothing else`;

    const aiResponse = await callOpenRouter([
      { role: "user", content: prompt },
    ]);

    if (
      !aiResponse.question ||
      !aiResponse.options ||
      !Array.isArray(aiResponse.options) ||
      aiResponse.options.length !== 4
    ) {
      throw new Error("Invalid AI response structure for question generation");
    }

    for (const opt of aiResponse.options) {
      if (!opt.text || !opt.traits || !Array.isArray(opt.traits)) {
        throw new Error("Invalid option structure in AI response");
      }
    }

    return res.status(200).json({
      success: true,
      question: aiResponse.question,
      category: aiResponse.category || "general",
      options: aiResponse.options,
    });
  } catch (error) {
    console.error("Error generating next question:", error.message);
    res.status(500).json({
      success: false,
      message: "Something went wrong generating the question. Please try again.",
      error: error.message,
    });
  }
});

// POST /api/assessment/final-result — Analyze all answers and generate career recommendations
router.post("/final-result", authMiddleware, async (req, res) => {
  try {
    const { allQnA } = req.body;

    if (!allQnA || !Array.isArray(allQnA) || allQnA.length === 0) {
      return res.status(400).json({
        success: false,
        message: "allQnA array is required with all assessment answers",
      });
    }

    // Build comprehensive analysis prompt
    const qnaHistory = allQnA
      .map(
        (qna, i) =>
          `Q${i + 1} (${qna.category}): ${qna.question}\nAnswer: ${qna.answer}\nTraits revealed: ${qna.traits.join(", ")}`
      )
      .join("\n\n");

    // Collect all traits
    const allTraits = allQnA.flatMap((qna) => qna.traits);
    const traitCounts = {};
    allTraits.forEach((t) => {
      traitCounts[t] = (traitCounts[t] || 0) + 1;
    });
    const topTraits = Object.entries(traitCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10)
      .map(([trait]) => trait);

    const prompt = `Analyze this career assessment for an Indian student and provide personalized career recommendations.

Complete Assessment Responses:
${qnaHistory}

Dominant traits (ranked by frequency): ${topTraits.join(", ")}

Based on ALL the answers and traits above, provide career recommendations. Return EXACTLY this JSON structure:
{
  "summary": "A 1-2 sentence personality and career profile of this student based on their answers",
  "careers": [
    {
      "title": "Career Title",
      "matchPercent": 87,
      "whyItFits": "2-3 sentence explanation of why this career matches this specific student based on their answers",
      "stream": "Science/Commerce/Arts/Technology",
      "skillsToLearn": ["Skill 1", "Skill 2", "Skill 3"],
      "topColleges": ["College 1, City", "College 2, City", "College 3, City"]
    }
  ]
}

Rules:
- Provide exactly 5 career recommendations
- Match percentages should be REALISTIC and VARIED — NOT all above 85%. Range from 60% to 95% based on actual fit
- The top career should have the highest percentage, with others decreasing realistically
- "whyItFits" must reference the student's SPECIFIC answers and traits, not generic descriptions
- Include Indian colleges/universities that are actually relevant
- Each career should be from a different domain if possible
- skillsToLearn should be specific, actionable skills the student should develop
- Return ONLY the JSON object, nothing else`;

    const aiResponse = await callOpenRouter([
      { role: "user", content: prompt },
    ]);

    // Validate response structure
    if (!aiResponse.summary || !aiResponse.careers || !Array.isArray(aiResponse.careers)) {
      throw new Error("Invalid AI response structure for final results");
    }

    // Validate each career entry
    for (const career of aiResponse.careers) {
      if (
        !career.title ||
        typeof career.matchPercent !== "number" ||
        !career.whyItFits ||
        !career.stream
      ) {
        throw new Error("Invalid career entry in AI response");
      }
      // Ensure arrays exist with defaults
      career.skillsToLearn = career.skillsToLearn || ["Research this field", "Build projects", "Network with professionals"];
      career.topColleges = career.topColleges || ["Check NIRF rankings", "Explore local universities", "Consider online programs"];
    }

    // Sort careers by matchPercent descending
    aiResponse.careers.sort((a, b) => b.matchPercent - a.matchPercent);

    // Save to user's assessment history
    try {
      const userId = req.userId;
      const user = await User.findById(userId);
      if (user) {
        const topCareer = aiResponse.careers[0];
        user.recommendedCareer = topCareer.title;
        user.assessmentHistory.push({
          recommendedCareer: topCareer.title,
          scores: {
            engineering: 0,
            medical: 0,
            design: 0,
            business: 0,
            it: 0,
            government: 0,
          },
          matchPercentage: topCareer.matchPercent,
          takenAt: new Date(),
          aiResult: {
            summary: aiResponse.summary,
            careers: aiResponse.careers,
          },
        });
        await user.save();
      }
    } catch (saveError) {
      console.error("Error saving assessment history:", saveError.message);
    }

    return res.status(200).json({
      success: true,
      summary: aiResponse.summary,
      careers: aiResponse.careers,
    });
  } catch (error) {
    console.error("Error generating final results:", error.message);
    res.status(500).json({
      success: false,
      message: "Something went wrong analyzing your responses. Please try again.",
      error: error.message,
    });
  }
});

// GET /api/assessment/history — Fetch logged-in user's assessment history
router.get("/history", authMiddleware, async (req, res) => {
  try {
    const user = await User.findById(req.userId).select("assessmentHistory");
    if (!user) {
      return res.status(404).json({ success: false, message: "User not found" });
    }
    // Return newest first
    const history = [...user.assessmentHistory].reverse();
    res.status(200).json({ success: true, history });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Error fetching assessment history",
      error: error.message,
    });
  }
});

module.exports = router;
